version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/danial/DB/postgres/db:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    environment:
      - PORT=8000
      - JWT_KEY=ag5sd1g6s4d6465s
      - DB_DRIVER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - SSL_MODE=disable
    ports:
      - '8000:8000'
    volumes:
      - .:/application
    depends_on:
      - db

volumes:
  db:
    driver: local
