FROM golang:alpine AS dev

WORKDIR /application

COPY go.mod .
RUN go mod download

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build ./src/main.go" --command="./main"